TAXONOMY_TAGS = [
    ("CLIENT_TYPE", "BANK", "Bank"),
    ("CLIENT_TYPE", "HF_MACRO", "HF Macro"),
    ("CLIENT_TYPE", "HF_RELVAL", "HF Relative Value"),
    ("CLIENT_TYPE", "HF_SYSTEMATIC", "HF Systematic"),
    ("CLIENT_TYPE", "ASSET_MANAGER_LONG_ONLY", "Asset Manager Long Only"),
    ("CLIENT_TYPE", "ASSET_MANAGER_MULTI_ASSET", "Asset Manager Multi Asset"),
    ("CLIENT_TYPE", "PENSION_INSURANCE", "Pension Insurance"),
    ("CLIENT_TYPE", "CORPORATE_TREASURY", "Corporate Treasury"),
    ("CLIENT_TYPE", "OFFICIAL_SOVEREIGN", "Official Sovereign"),
    ("PRODUCT", "FX_SPOT_FWD_NDF", "FX Spot Forward NDF"),
    ("PRODUCT", "FX_VANILLA_OPTION", "FX Vanilla Option"),
    ("PRODUCT", "FX_EXOTIC_BARRIER_DIGITAL", "FX Exotic Barrier Digital"),
    ("PRODUCT", "FX_VOL_STRUCTURE", "FX Vol Structure"),
    ("PRODUCT", "RATES_SWAP_OIS_BASIS", "Rates Swap OIS Basis"),
    ("PRODUCT", "RATES_OPTIONS", "Rates Options"),
    ("PRODUCT", "BOND_CASH_SOV_CORP", "Bond Cash Sovereign Corporate"),
    ("PRODUCT", "BOND_DERIV_OVERLAY", "Bond Derivative Overlay"),
    ("PRODUCT", "CROSS_ASSET_PACKAGE", "Cross Asset Package"),
    ("INTENT", "HEDGING", "Hedging"),
    ("INTENT", "YIELD_ENHANCEMENT", "Yield Enhancement"),
    ("INTENT", "DIRECTIONAL_VIEW", "Directional View"),
    ("INTENT", "VOLATILITY_VIEW", "Volatility View"),
    ("INTENT", "RELATIVE_VALUE", "Relative Value"),
    ("INTENT", "TAIL_PROTECTION", "Tail Protection"),
    ("INTENT", "CARRY", "Carry"),
    ("INTENT", "CURVE_EXPRESSION", "Curve Expression"),
    ("RISK", "LOW_DELTA", "Low Delta"),
    ("RISK", "HIGH_CONVEXITY", "High Convexity"),
    ("RISK", "KNOCK_IN", "Knock In"),
    ("RISK", "KNOCK_OUT", "Knock Out"),
    ("RISK", "CAPITAL_PROTECTED", "Capital Protected"),
    ("RISK", "LEVERED", "Levered"),
    ("RISK", "PATH_DEPENDENT", "Path Dependent"),
    ("RISK", "DRAWDOWN_SENSITIVE", "Drawdown Sensitive"),
    ("TENOR", "INTRADAY", "Intraday"),
    ("TENOR", "1W_1M", "1W 1M"),
    ("TENOR", "1M_3M", "1M 3M"),
    ("TENOR", "3M_12M", "3M 12M"),
    ("TENOR", "1Y_PLUS", "1Y Plus"),
    ("MARKET", "G10_FX", "G10 FX"),
    ("MARKET", "EM_ASIA_FX", "EM Asia FX"),
    ("MARKET", "EM_LATAM_FX", "EM Latam FX"),
    ("MARKET", "EMEA_FX", "EMEA FX"),
    ("MARKET", "USD_RATES", "USD Rates"),
    ("MARKET", "EUR_RATES", "EUR Rates"),
    ("MARKET", "LOCAL_RATES", "Local Rates"),
    ("MARKET", "IG_CREDIT", "IG Credit"),
    ("MARKET", "HY_CREDIT", "HY Credit"),
    ("THEME", "CENTRAL_BANK", "Central Bank"),
    ("THEME", "INFLATION", "Inflation"),
    ("THEME", "MACRO_DATA", "Macro Data"),
    ("THEME", "ELECTION_GEO", "Election Geo"),
    ("THEME", "SUPPLY_DEMAND_BONDS", "Supply Demand Bonds"),
    ("THEME", "RISK_ON_OFF", "Risk On Off"),
    ("THEME", "POLICY_DIVERGENCE", "Policy Divergence"),
    ("BEHAVIOR", "PREFERS_SIMPLE", "Prefers Simple"),
    ("BEHAVIOR", "LIKES_COMPLEX", "Likes Complex"),
    ("BEHAVIOR", "FAST_DECISION", "Fast Decision"),
    ("BEHAVIOR", "EDUCATION_NEEDED", "Education Needed"),
    ("BEHAVIOR", "LARGE_TICKET", "Large Ticket"),
    ("BEHAVIOR", "SMALL_TICKET", "Small Ticket"),
]


DEFAULT_SYNONYMS = [
    ("ndf", "fx spot fwd ndf", "FX_SPOT_FWD_NDF"),
    ("forward", "fx spot fwd ndf", "FX_SPOT_FWD_NDF"),
    ("fx forward", "fx spot fwd ndf", "FX_SPOT_FWD_NDF"),
    ("vanilla option", "fx vanilla option", "FX_VANILLA_OPTION"),
    ("digital", "fx exotic barrier digital", "FX_EXOTIC_BARRIER_DIGITAL"),
    ("barrier", "fx exotic barrier digital", "FX_EXOTIC_BARRIER_DIGITAL"),
    ("barrier option", "fx exotic barrier digital", "FX_EXOTIC_BARRIER_DIGITAL"),
    ("rr", "risk reversal", "FX_VOL_STRUCTURE"),
    ("risk reversal", "fx vol structure", "FX_VOL_STRUCTURE"),
    ("seagull", "fx vol structure", "FX_VOL_STRUCTURE"),
    ("collar", "fx vol structure", "FX_VOL_STRUCTURE"),
    ("swap", "rates swap ois basis", "RATES_SWAP_OIS_BASIS"),
    ("ois", "rates swap ois basis", "RATES_SWAP_OIS_BASIS"),
    ("basis swap", "rates swap ois basis", "RATES_SWAP_OIS_BASIS"),
    ("swaption", "rates options", "RATES_OPTIONS"),
    ("cap floor", "rates options", "RATES_OPTIONS"),
    ("credit overlay", "bond deriv overlay", "BOND_DERIV_OVERLAY"),
    ("cross asset", "cross asset package", "CROSS_ASSET_PACKAGE"),
    ("hedge", "hedging", "HEDGING"),
    ("protection", "tail protection", "TAIL_PROTECTION"),
    ("tail hedge", "tail protection", "TAIL_PROTECTION"),
    ("yield pickup", "yield enhancement", "YIELD_ENHANCEMENT"),
    ("carry basket", "carry", "CARRY"),
    ("rv", "relative value", "RELATIVE_VALUE"),
    ("relative value", "relative value", "RELATIVE_VALUE"),
    ("directional", "directional view", "DIRECTIONAL_VIEW"),
    ("vol view", "volatility view", "VOLATILITY_VIEW"),
    ("curve steepener", "curve expression", "CURVE_EXPRESSION"),
    ("curve flattener", "curve expression", "CURVE_EXPRESSION"),
    ("ki", "knock_in", "KNOCK_IN"),
    ("knock in", "knock_in", "KNOCK_IN"),
    ("ko", "knock_out", "KNOCK_OUT"),
    ("knock out", "knock_out", "KNOCK_OUT"),
    ("capital protected", "capital protected", "CAPITAL_PROTECTED"),
    ("leveraged", "levered", "LEVERED"),
    ("path dependent", "path dependent", "PATH_DEPENDENT"),
    ("drawdown", "drawdown sensitive", "DRAWDOWN_SENSITIVE"),
    ("intraday", "intraday", "INTRADAY"),
    ("1w", "1w 1m", "1W_1M"),
    ("1m", "1m 3m", "1M_3M"),
    ("3m", "3m 12m", "3M_12M"),
    ("1y", "1y plus", "1Y_PLUS"),
    ("g10", "g10 fx", "G10_FX"),
    ("em asia", "em asia fx", "EM_ASIA_FX"),
    ("latam", "em latam fx", "EM_LATAM_FX"),
    ("emea", "emea fx", "EMEA_FX"),
    ("usd rates", "usd rates", "USD_RATES"),
    ("eur rates", "eur rates", "EUR_RATES"),
    ("local rates", "local rates", "LOCAL_RATES"),
    ("ig", "ig credit", "IG_CREDIT"),
    ("high yield", "hy credit", "HY_CREDIT"),
    ("cb", "central bank", "CENTRAL_BANK"),
    ("central bank", "central bank", "CENTRAL_BANK"),
    ("cpi", "inflation", "INFLATION"),
    ("inflation", "inflation", "INFLATION"),
    ("nfp", "macro data", "MACRO_DATA"),
    ("payrolls", "macro data", "MACRO_DATA"),
    ("election", "election geo", "ELECTION_GEO"),
    ("geopolitics", "election geo", "ELECTION_GEO"),
    ("supply", "supply demand bonds", "SUPPLY_DEMAND_BONDS"),
    ("risk on", "risk on off", "RISK_ON_OFF"),
    ("risk off", "risk on off", "RISK_ON_OFF"),
    ("divergence", "policy divergence", "POLICY_DIVERGENCE"),
    ("simple", "prefers simple", "PREFERS_SIMPLE"),
    ("complex payoff", "likes complex", "LIKES_COMPLEX"),
    ("quick turnaround", "fast decision", "FAST_DECISION"),
    ("needs teach in", "education needed", "EDUCATION_NEEDED"),
    ("large size", "large ticket", "LARGE_TICKET"),
    ("small clips", "small ticket", "SMALL_TICKET"),
]
